server:
  port: ${BIBLIOS_PORT:8080}
spring:
  application:
    name: Biblios.io
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:127.0.0.1}:${POSTGRES_PORT:5432}/library
    username: ${POSTGRES_USER:bibliosuser}
    password: ${POSTGRES_PASS:bibliospass}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgresSQLDialect
        format_sql: true
    show-sql: true